site_name: Apunts del curs
site_description: Apunts SMX i DAM
site_author: Joan M.
theme:
  name: material
  font:
    text: 'Catamaran bold'
#  custom_dir: docs/overrides
  favicon: images/favicon.png
  extra_css:
    - stylesheets/extra.css
  language: ca
  logo: assets/images/logo.png
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  plugins:
    - typeset
    - search
  palette:
    # palette for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # palette for light mode
    - scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
  - pymdownx.highlight:
     anchor_linenums: true
     use_pygments: false
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.snippets

copyright: Copyright &copy; 2024 Joan M. 
# extra_css:
#  - assets/stylesheets/extra.css
extra:
  generator: false
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/

nav:
  - Index: index.md

  - CFGS ASIX ICA0: 
    - Mòduls ICA0: ica0-Asix/ica0.md

    - MP02 Gestió de bases de dades: 
      - MP02: ica0-Asix/mp02/mp02.md

      - Unitat d'aprenentatge 1:
        - UA1 - Introducció a les bases de dades: ica0-Asix/mp02/ua1/0372-ua1-index.md
        - Nucli Formatiu 1: ica0-Asix/mp02/ua1/0372-ua1-nf1.md
        - Nucli Formatiu 2: ica0-Asix/mp02/ua1/0372-ua1-nf2.md
        - Nucli Formatiu 3: ica0-Asix/mp02/ua1/0372-ua1-nf3.md
        - Nucli Formatiu 4: ica0-Asix/mp02/ua1/0372-ua1-nf4.md

      - Unitat d'aprenentatge 2:
        - UA2 - Llenguatges SQL. DDL i DML: ica0-Asix/mp02/ua2/0372-ua2-index.md
        - Nucli Formatiu 1: ica0-Asix/mp02/ua2/0372-ua2-nf1.md
        - Nucli Formatiu 2: ica0-Asix/mp02/ua2/0372-ua2-nf2.md
        - Nucli Formatiu 3: ica0-Asix/mp02/ua2/0372-ua2-nf3.md
        - Nucli Formatiu 4: ica0-Asix/mp02/ua2/0372-ua2-nf4.md

      - Unitat d'aprenentatge 3:
        - UA3 - Assegurament de la informació: ica0-Asix/mp02/ua3/0372-ua3-index.md
        - Nucli Formatiu 1: ica0-Asix/mp02/ua3/0372-ua3-nf1.md
        - Nucli Formatiu 2: ica0-Asix/mp02/ua3/0372-ua3-nf2.md

  - CFGM SMX IC10:
    - Mòduls IC10: 
      - Llistat de mòduls: ic10-Smx/ic10.md

      - 1r curs: 
        - Anglès professional: ic10-Smx/0156-ANG/0156.md
        - Muntatge i manteniment d’equips: ic10-Smx/0221-MME/0221.md
        - Sistemes operatius monolloc: ic10-Smx/0222-SOM/0222.md
        - Aplicacions ofimàtiques: ic10-Smx/0223-AOF/0223.md
        - Xarxes locals: ic10-Smx/0225-XL/0225.md
        - Aplicacions web: ic10-Smx/0228-AWEB/0228.md
        - Digitalització: ic10-Smx/1664-DIG/1664.md
        - Sostenibilitat: ic10-Smx/1708-SOST/1708.md
        - IPO 1: ic10-Smx/1709-IPO1/1709.md
        - Creació de pàgines web: ic10-Smx/OPT1SMX/OPT1SMX.md

      - 2n curs: 
        - Sistemes operatius en xarxa: ic10-Smx/0224-SOX/0224.md
        - Seguretat informàtica: ic10-Smx/0226-SI/0226.md
        - Serveis de xarxa: ic10-Smx/0227-SX/RA1-DHCP/0227-RA1.md
          - RA1 Servidor DHCP: ic10-Smx/0227-SX/0227.md
        - IPO 2: ic10-Smx/1710-IPO2/1710.md
        - Projecte intermodular: ic10-Smx/1713-PRO/1713.md
        - Programació bàsica: ic10-Smx/OPT2SMX/OPT2SMX.md


